language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  # Install binary pandoc from Rstudio
  - mkdir -p $HOME/opt/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
      -d $HOME/opt/pandoc
  - chmod +x $HOME/opt/pandoc/pandoc*
  - rm pandoc-1.12.3.zip
  - $HOME/opt/pandoc/pandoc --version

  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - global:
    - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
